apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
        - name: my-react-app-container
          image: ghcr.io/gagan4580/my-react-app:bb93870c99fc07fce8e83ac8ad2a0da333aade2c
        
