apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
        - name: my-react-app-container
          image: ghcr.io/gagan4580/my-react-app:e9c2501252b4ae235e584708a963be7b2d6729cf
        
